name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]
   
jobs:

  codecov:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        show-progress: false


    - name: Test and generate code coverage report
      run: xcrun xcodebuild -skipPackagePluginValidation -enableCodeCoverage YES -scheme Lotsawa -destination 'platform=macOS' test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5.0.2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
        flags: unittests
