name: Publish Documentation

on:
  push:
    branches: [ "*" ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwcd/swift-docc-action@v1
      with:
        target: YourTarget
        output: ./docs
        hosting-base-path: yourproject
        disable-indexing: 'true'
        transform-for-static-hosting: 'true'
    - name: Commit docs
      run: |
        mv docs updated-docs
        git config --local user.email "bot@github.com"
        git config --local user.name "GitHub Actions"
        git fetch origin generated-docs
        git checkout --detach origin/generated-docs
        rm -rf ./docs
        mv updated-docs docs
        git add ./docs
        git commit -m "Update docs"
        git push origin HEAD:generated-docs
