name: Publish Documentation

on:
  push:
    branches: [ "*" ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: fwcd/swift-docc-action@v1
      with:
        target: Lotsawa
        output: ./docc
        hosting-base-path: Lotsawa/docc
        disable-indexing: true
        enable-inherited-docs: true
        experimental-documentation-coverage: true
        transform-for-static-hosting: true
        source-service: github
        source-service-base-url: "https://github.com/${GITHUB_REPOSITORY}/blob/${GITHUB_REF}"
        checkout-path: .
    - name: Install jazzy
      run: gem install jazzy
    - name: Run Jazzy
      run: |
        jazzy \
        --clean \
        --source-host-files-url "https://github.com/${GITHUB_REPOSITORY}/tree/${GITHUB_REF}" \
        --module-version "${{ github.event.release.tag_name }}" \
        --copyright "© $(date '+%Y') Dave Abrahams. (Last updated: $(date '+%Y-%m-%d'))" \
        --config .jazzy.yml \
        --output jazzy
    - name: Commit docs
      run: |
        git config --local user.email "bot@github.com"
        git config --local user.name "GitHub Actions"
        git fetch origin generated-docs
        git checkout --detach origin/generated-docs
        rm -rf ./docs/*
        mv docc jazzy docs
        git add ./docs
        git commit -m "Update docs"
        git push origin HEAD:generated-docs
