name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]
   
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests
    - name: Run tests
      run: swift test
  xcode:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcrun xcodebuild -skipPackagePluginValidation -scheme Lotsawa -destination 'platform=macOS'
  linux:
    container:
      image: swift:${{ matrix.linux }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: [bionic, focal]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests --enable-test-discovery
    - name: Test
      run: swift test --enable-test-discovery
  codecov:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test and generate code coverage report
      run: xcrun xcodebuild -skipPackagePluginValidation -enableCodeCoverage YES -scheme Lotsawa -destination 'platform=macOS' test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
